"""datapoint table

Revision ID: f9d319783444
Revises: 49fee9834ff7
Create Date: 2023-10-03 07:47:57.425149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d319783444'
down_revision = '49fee9834ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datapoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datapoint_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datapoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datapoint_timestamp'))

    op.drop_table('datapoint')
    # ### end Alembic commands ###
